STAGE_ID=axis
PROD_ID=axis
PDF_DOWNLOAD_LOC=/Users/loaner/Desktop/Optimus/all_variants/
EXPECTED_DIR=/Users/loaner/Desktop/Optimus/BB_new/P/
STAGE_DIR=/Users/loaner/Desktop/Optimus/BB_new/S/
RESULT_DIR=/Users/loaner/Desktop/Code/TH_DEVELOP/test_harness/src/test/resources/Results/
PARSER_NAME=OPTIMUS
COMPARISON_MODE=PROD
FILE_IDS_CSV=
//Users/loaner/Desktop/axis_3.csv
MANDATORY_FIELDS_CSV=/Users/loaner/Desktop/Code/TH_DEVELOP/test_harness/src/test/resources/allfields_bb.csv
KEY_FILTER=transformed_data.statement_details.account_summary*
//json_object.statement_details.transactions.domestic_transactions*,json_object.statement_details.account_summary*



