/ParserDetails
PRIMARY_PARSER_NAME=PANDORASTREET
SECONDARY_PARSER_NAME=BUMBLEBEE
ISSUER=HDFC Bank
PRIMARY_PARSER_TEMPLATE_ID=hdfc
SECONDARY_PARSER_TEMPLATE_ID=hdfc
PRIMARY_PARSER_ENV=STAGE
SECONDARY_PARSER_ENV=STAGE
COMPARISON_MODE=SECONDARY
SECONDARY_MODE_STANDALONE_ANALYSIS_DISABLED=false
PDF_DOWNLOAD_LOC=/Users/loaner/Desktop/Code/TH_DEVELOP/test_harness/src/test/resources/PDFs/
PRIMARY_DIR=/Users/loaner/Desktop/Code/TH_DEVELOP/test_harness/src/test/resources/PrimaryResponses/
SECONDARY_DIR=/Users/loaner/Desktop/Code/TH_DEVELOP/test_harness/src/test/resources/SecondaryResponses/
RESULT_DIR=/Users/loaner/Desktop/Code/TH_DEVELOP/test_harness/src/test/resources/Results/
FILE_IDS_CSV=/Users/loaner/Downloads/hdfc25.csv
KEY_FILTER=**


//CONCURRENCY_AND_RATE_LIMIT_Details
NUM_DOWNLOAD_THREADS=3
DOWNLOAD_RATELIMIT=1.0
NUM_PRIMARYPARSER_THREADS=5
PRIMARY_PARSER_RATELIMIT=7.5
NUM_SECONDARYPARSER_THREADS=5
SECONDARY_PARSER_RATELIMIT=2.5


//API_URLS
BUMBLEBEE_FQDN=http://bumblebee.%s.dreamplug.net/xfmr/v1/pdf2data
OPTIMUS_FQDN=http://optimus.%s.dreamplug.net/pdf_to_json/file_stream/test/%s
PANDORASTREET_FQDN=http://pandorastreet.%s.dreamplug.net/rocketpdf/api/test/pdf
STATEMENT_GENERATION_API_FQDN=http://statement-service.stg.dreamplug.net/statement/consumer/consolidate