STAGE_ID=axis
PROD_ID=axis.creditcard
PDF_DOWNLOAD_LOC=/Users/loaner/Desktop/Optimus/null/
EXPECTED_DIR=/Users/loaner/Desktop/Optimus/prod/
STAGE_DIR=/Users/loaner/Desktop/Optimus/stg/
RESULT_DIR=/Users/loaner/Desktop/Code/TH_DEVELOP/test_harness/src/test/resources/Results/
PARSER_NAME=OPTIMUS
COMPARISON_MODE=PROD
FILE_IDS_CSV=/Users/loaner/Desktop/axis_3.csv
MANDATORY_FIELDS_CSV=/Users/loaner/Desktop/mf3.csv
KEY_FILTER=**
//json_object.statement_details.transactions.domestic_transactions*,json_object.statement_details.account_summary*


